version: '3.8'

services:
  feedgen:
    build: .
    container_name: bsky-feedgen
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./feed_database.db:/app/feed_database.db
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - feedgen-network

networks:
  feedgen-network:
    driver: bridge
